name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and deploy to staging
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.STAGING_HOST }} << 'EOF'
            cd ~/arkam-staging/frontend
            git pull origin staging
            docker compose -f docker-compose.staging.yml up -d --build
            docker image prune -f
          EOF